plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'PanillaX'

// api
include 'panillax-api'

// paper NMS implementation bundles
include 'panillax-paper-v1_21_4'
include 'panillax-paper-v1_21_5'
include 'panillax-paper-v1_21_11'

// paper main module
include 'panillax-paper'

// api
project(':panillax-api').projectDir = file('api')

// paper NMS implementation bundles
project(':panillax-paper-v1_21_4').projectDir = file('paper-v1_21_4')
project(':panillax-paper-v1_21_5').projectDir = file('paper-v1_21_5')
project(':panillax-paper-v1_21_11').projectDir = file('paper-v1_21_11')

// paper main module
project(':panillax-paper').projectDir = file('paper')
